Setup PowerShell scripts to simplify development
AlpsBTE/alpsbte-website pull request #25
Opened 2021-08-22 19:21 UTC by b3h3m0th

closes #24

2021-08-22 20:32 UTC, patrickcerny requested changes
Looks nice! Does this close the Docker issue? And please remove / explain the angular thingy there! All in all nice work!

2021-08-22 20:32 UTC, patrickcerny commented on .vscode/extensions.json
> +    "angular.ng-template"
angular.ng-template in a react project?

2021-08-22 20:37 UTC, b3h3m0th commented
Boa wieso schriban mir uf englisch?

2021-08-22 20:39 UTC, b3h3m0th commented
Und na i krig des mit docker iwi ned gschissa. joa des docker issue kama eig closen.

2021-08-22 20:40 UTC, Georg-code commented
We are international af

2021-08-23 08:09 UTC, b3h3m0th commented on .vscode/extensions.json
> +    "angular.ng-template"
lol isch recht

2021-08-23 08:31 UTC, patrickcerny approved these changes

2021-08-23 08:49 UTC, merged