19 home heading
AlpsBTE/alpsbte-website pull request #34
Opened 2021-08-23 16:19 UTC by Georg-code

Home heading

2021-08-23 21:39 UTC, patrickcerny requested changes
All in all, it looks nice! Please think about the changes i proposed and then I think we are good to go.

2021-08-23 21:39 UTC, patrickcerny commented on libs/shared/components/src/lib/button/button.tsx
> +  marginTop?: string;
Rather than adding all styles one by one, add a `styles` property which is then mapped to the styles prop of the button,

2021-08-23 21:39 UTC, patrickcerny commented on libs/shared/components/src/lib/button/button.tsx
> +        marginLeft: props.center ? 'auto' : 'unset',
As I said, i like the idea, but dont cherrypick the css props unless it's really needed,

2021-09-13 15:23 UTC, Georg-code commented
Irrelevenat, cause there was a new pr that implemented that

2021-09-13 15:23 UTC, closed without merging